add_newline = false

# Replace the "❯" symbol in the prompt with "❯❯"
[character]
format = "❯❯ "
success_symbol = "❯❯(bold green) "
error_symbol = "❯❯(bold red) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable the AWS module.
[aws]
disabled = true

# Set the time format
[time]
disabled = false
time_format = "%d-%m-%Y %R"
utc_time_offset = "-5"

# Directory setttings
[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[username]
disabled = true

[hostname]
ssh_only = false
format =  "[$hostname](bold red) ❯ "
